cmake_minimum_required(VERSION 3.19)
project(markoff_view_qml_tests LANGUAGES CXX)
enable_testing()
find_package(Qt6 REQUIRED COMPONENTS Test)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)

add_executable(tst_view_qml_editor_backend tst_view_qml_editor_backend.cpp)
add_test(NAME tst_view_qml_editor_backend COMMAND tst_view_qml_editor_backend)
target_link_libraries(tst_view_qml_editor_backend PRIVATE Qt6::Test markoff_view_qml)
set_tests_properties(tst_view_qml_editor_backend PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
